CHAT_MESSAGE = "chat_message"
ERROR = "error"
RECIPIENT_CHOSEN = "recipient_chosen"
RECIPIENT_NOT_CONNECTED = "recipient_not_connected"
CONNECTED_USERS = "connected_users"
ROOM_KILLED = "room_killed"
